export const venues = {
    "heritage": "Heritage",
    "privatesale": "Private Sale",
    "comicconnect": "ComicConnect",
    "ebay": "eBay",
    "comiclink": "ComicLink",
    "goldinauctions": "Goldin Auctions",
    "unknown": "unknown",
    "metropolis": "Metropolis",
    "hakes": "Hakes",
    "pedigreecomics": "Pedigree Comics",
    "mastronet": "Mastronet",
    "mycomicshopcom": "MyComicShop.com",
    "philipweiss": "Philip Weiss",
    "highgradecomics": "High Grade Comics",
    "redbeard": "Red Beard",
    "pgcmint": "PGCMint",
    "jphemint": "JP The Mint",
    "gregreece": "Greg Reece Comics",
    "esquirecomics": "Esquire Comics/Comic Connect",
    "sothebys": "Sotheby's",
    "landry":"Landry Pop Acutions"
};